name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '* * * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        name: Login to DockerHub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Runs a single command using the runners shell
      - name: Build all the required version of the container, use the SaltStack releases.
        run: bash .scripts/build-publish.sh