name: CI

on:
  pull_request:
    branches:
      - testing

jobs:
  check:
    name: Check the code
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Shellcheck all the .scripts
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './.scripts'

      - name: Check the dockerfile
        uses: brpaz/hadolint-action@master